#!/usr/bin/env bash
# Sourced by login shells only

# Load .profile, containing login, non-bash related initializations.
[[ -e ~/.profile ]] && source ~/.profile

# Load .bashrc, containing non-login related bash initializations.
[[ -e ~/.bashrc ]] && source ~/.bashrc
