#!/usr/bin/env bash
# http://tldp.org/LDP/abs/html/sample-bashrc.html
# https://github.com/andschwa/dotfiles

# Make some possibly destructive commands more interactive
alias rm="rm -i"  # Interactive mode delete
alias mv="mv -i"
alias cp="cp -i"

alias mkdir="mkdir -pv"  # Creates parent directories if needed
alias path="echo -e ${PATH//:/\\n}"

# Niceities
alias cd..="cd .."
alias hs="cd ~/ && ls"
alias up="cd .."
alias home="cd ~/"
alias root="sudo su"
alias hist="history"
alias jobs="jobs -l"

# Grep shorthands
alias grep="grep --color=auto --exclude-dir=\.git"  # Colorize grep command output + skip .git directories

# ls shorthands
alias l.="ls -d .* --color=auto"
alias ls="ls -CF --color=auto"  # Make 'normal' ls nice with Columns and Colors
alias lm="ls -lhAF --color=auto | more"  # For big directories
alias ll="ls -lv --group-directories-first"
alias la="ls -AF --color=auto"
alias lar="ls -lhAR --color=auto | more"  # Recursive subdirectories, listed out
alias lcr="ls -CAR --color=auto | more"  # Recursive subdirectories, by column
alias lh="ls -lAhF --color=auto"
alias lx='ls -lXB'  # Sort by extension
alias lt='ls -ltr'  # Sort by date, most recent last
alias tree='tree -Csuh'  # Nice alternative to 'recursive ls'

# Time
alias now="date +"%T""
alias nowtime=now
alias nowdate="date +\"%d-%m-%Y\""

# Networking
alias ports="netstat -tulanp"
alias ping="ping -c 4"

# Fancy git log
alias gl="git log --graph --decorate --name-status --all"

# Colorful tmux
alias tmux="TERM=xterm-256color tmux"

# cppcheck
alias cppc="cppcheck --enable=all --suppress=missingIncludeSystem ."
